export default Object.freeze({
  TRIPS: "Trips",
  PAYOUTS_AIRTEL: "PayoutsToAirtel",
  PAYOUTS_BANK: "PayoutsToBank",
  PAYOUTS_MPESA: "PayoutsToMpesa",
  PAYOUTS_PAYBILL: "PayoutsToPaybill",
  PAYOUTS_TILL: "PayoutsToTill",
  VEHICLES: "Vehicles",
  VEHICLE_DETAILS: "VehicleDetails",
  VEHICLE_COLLECTION: "VehicleCollection",
  VEHICLE_CREW: "VehicleCrew",
  VEHICLE_PAYOUTS: "VehiclePayouts",
  VEHICLE_SUBSCRIPTIONS: "VehicleSubscriptions",
  VEHICLE_TRIPS: "VehicleTrips",
  ACCOUNTS: "Accounts",
  SACCO: "Sacco",
  WALLET: "Wallet",
});
